const development = {
  projectCreateTime: new Date(),
  NO: 1,
  productPortNo: '3590A-400',
  ESEndTime: new Date(),
  parentType: '手机',
  type: '后置',
  apply: '景深',
  projectType: '立项变更',
  newType: '量产变形',
  shapeSize: 'M5*0.25',
  isUltraThin: 0,
  isLittleHead: 0,
  isLargeImage: 0,
  isLargeAperture: 0,
  customer: 'moto',
  background: '3586A换料号外推MOTO',
  complexity: '一般',
  preDRTime: new Date(),
  prePlotTime: new Date(),
  DRTime: new Date(),
  PlotTime: new Date(),
  department: '制造',
  remark: '',
  opticalBear: '谢检来',
  structureBear: '戴世浩',
  PM: '',
  TTL: 2.9,
  FNO: 2.4,
  FOV: 83,
  structure: '3P',
  headDia: '',
  depth: ''
}